"""Project Folder Creator — post-approval Project Setup Generator.

Creates the on-disk scaffold inside outputs/ with the required structure:

    outputs/
    ├── frontend/
    ├── backend/
    ├── database/
    ├── shared/
    └── metadata/

File content is generated by the LLM based on the actual blueprint so every
file reflects the real project rather than a generic template.
"""

import json
import os
from typing import Any, Dict, List

from app.utils.logger import get_logger
from app.utils.json_utils import safe_extract_json

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# LLM system prompts
# ---------------------------------------------------------------------------

_SYSTEM_BACKEND = """You are a senior backend engineer.
Generate production-ready starter files for a backend service.
Return ONLY a single valid JSON object — no prose, no markdown fences.

Schema:
{
  "files": [
    {
      "path": "<relative path inside backend/, e.g. app/main.py>",
      "content": "<full file content as a string>"
    }
  ]
}

Requirements:
- Include: entry point, config loader, health check endpoint, one service stub per module,
  one model stub per entity, requirements.txt / package.json.
- All files must be complete and syntactically correct.
- Use the exact tech stack, project name, module names and entity names provided.
"""

_SYSTEM_FRONTEND = """You are a senior frontend engineer.
Generate production-ready starter files for a frontend application.
Return ONLY a single valid JSON object — no prose, no markdown fences.

Schema:
{
  "files": [
    {
      "path": "<relative path inside frontend/, e.g. src/App.jsx>",
      "content": "<full file content as a string>"
    }
  ]
}

Requirements:
- Include: entry point, App root component, one page component per feature,
  a shared api client stub, package.json.
- All files must be complete and syntactically correct.
- Use the exact tech stack and feature names provided.
"""

_SYSTEM_DATABASE = """You are a database architect.
Generate the database schema DDL and a seed file.
Return ONLY a single valid JSON object — no prose, no markdown fences.

Schema:
{
  "files": [
    {
      "path": "<relative path inside database/, e.g. schema.sql>",
      "content": "<full file content as a string>"
    }
  ]
}

Requirements:
- schema.sql: CREATE TABLE statements for all entities with correct types, PKs, FKs.
- seed.sql: INSERT statements with representative sample data.
- migrations/001_initial.sql: same CREATE TABLE statements wrapped in a migration.
"""

_SYSTEM_SHARED = """You are a senior software engineer.
Generate shared utility files usable by both frontend and backend.
Return ONLY a single valid JSON object — no prose, no markdown fences.

Schema:
{
  "files": [
    {
      "path": "<relative path inside shared/>",
      "content": "<full file content as a string>"
    }
  ]
}

Requirements:
- constants (language-appropriate)
- error/exception classes
- logger utility
- pagination helper
- auth middleware stub
- typed DTOs / interfaces per entity
- API contracts JSON per module (one file per module under contracts/)
"""


class ProjectFolderCreator:
    """LLM-driven post-approval scaffold generator.

    Creates outputs/frontend/, outputs/backend/, outputs/database/,
    outputs/shared/, and outputs/metadata/ with real, project-specific content.
    """

    def __init__(self, llm=None) -> None:
        self._llm = llm

    def create(
        self,
        project_name: str,
        tech_stack: Dict[str, str],
        modules: List[Dict[str, Any]],
        entities: List[Dict[str, Any]],
        features: List[Dict[str, Any]],
        shared_components: List[Dict[str, Any]],
        base_dir: str,
    ) -> Dict[str, Any]:
        """Generate the full project scaffold.

        Args:
            project_name:      Human-readable project name.
            tech_stack:        Dict with backend/frontend/database/infrastructure.
            modules:           Module list from MasterBlueprint.
            entities:          Entity list from DataModelAnalyzer.
            features:          Feature list from FeatureIdentifier.
            shared_components: Shared component list.
            base_dir:          Root outputs directory.

        Returns:
            Dict with 'project_root', 'folders', 'files' keys.
        """
        project_root = base_dir  # scaffold goes directly into outputs/
        created_folders: List[str] = []
        created_files: List[str] = []

        context = self._build_context(project_name, tech_stack, modules, entities, features)

        # Generate each layer
        self._generate_backend(project_root, context, tech_stack, modules, entities, features, created_folders, created_files)
        self._generate_frontend(project_root, context, tech_stack, features, created_folders, created_files)
        self._generate_database(project_root, context, tech_stack, entities, created_folders, created_files)
        self._generate_shared(project_root, context, tech_stack, modules, entities, shared_components, created_folders, created_files)
        self._generate_metadata(project_root, project_name, tech_stack, modules, entities, features, shared_components, created_folders, created_files)

        return {
            "project_root": project_root,
            "folders": created_folders,
            "files": created_files,
        }

    # ------------------------------------------------------------------
    # Layer generators
    # ------------------------------------------------------------------

    def _generate_backend(self, project_root, context, tech_stack, modules, entities, features, folder_log, file_log):
        backend_dir = os.path.join(project_root, "backend")
        self._ensure_dir(backend_dir, folder_log)

        if self._llm:
            user_prompt = (
                f"{context}\n\n"
                f"Backend tech: {tech_stack.get('backend')}\n"
                f"Modules: {json.dumps(modules)}\n"
                f"Entities: {json.dumps(entities)}\n"
                f"Features: {json.dumps([f['name'] for f in features])}"
            )
            logger.info("ProjectFolderCreator: generating backend files via LLM")
            raw = self._llm.complete(_SYSTEM_BACKEND, user_prompt, max_tokens=6000)
            result = safe_extract_json(raw, fallback={"files": []})
            self._write_files(backend_dir, result.get("files", []), file_log, folder_log)
        else:
            self._write_fallback_backend(backend_dir, tech_stack, modules, entities, file_log, folder_log)

    def _generate_frontend(self, project_root, context, tech_stack, features, folder_log, file_log):
        frontend_dir = os.path.join(project_root, "frontend")
        self._ensure_dir(frontend_dir, folder_log)

        if self._llm:
            user_prompt = (
                f"{context}\n\n"
                f"Frontend tech: {tech_stack.get('frontend')}\n"
                f"Features: {json.dumps([f['name'] for f in features])}"
            )
            logger.info("ProjectFolderCreator: generating frontend files via LLM")
            raw = self._llm.complete(_SYSTEM_FRONTEND, user_prompt, max_tokens=6000)
            result = safe_extract_json(raw, fallback={"files": []})
            self._write_files(frontend_dir, result.get("files", []), file_log, folder_log)
        else:
            self._write_fallback_frontend(frontend_dir, tech_stack, features, file_log, folder_log)

    def _generate_database(self, project_root, context, tech_stack, entities, folder_log, file_log):
        database_dir = os.path.join(project_root, "database")
        migrations_dir = os.path.join(database_dir, "migrations")
        self._ensure_dir(database_dir, folder_log)
        self._ensure_dir(migrations_dir, folder_log)

        if self._llm:
            user_prompt = (
                f"{context}\n\n"
                f"Database: {tech_stack.get('database')}\n"
                f"Entities: {json.dumps(entities)}"
            )
            logger.info("ProjectFolderCreator: generating database files via LLM")
            raw = self._llm.complete(_SYSTEM_DATABASE, user_prompt, max_tokens=4000)
            result = safe_extract_json(raw, fallback={"files": []})
            self._write_files(database_dir, result.get("files", []), file_log, folder_log)
        else:
            self._write_fallback_database(database_dir, entities, file_log)

    def _generate_shared(self, project_root, context, tech_stack, modules, entities, shared_components, folder_log, file_log):
        shared_dir = os.path.join(project_root, "shared")
        self._ensure_dir(shared_dir, folder_log)

        if self._llm:
            user_prompt = (
                f"{context}\n\n"
                f"Backend tech: {tech_stack.get('backend')}\n"
                f"Modules: {json.dumps([m['name'] for m in modules])}\n"
                f"Entities: {json.dumps([e['name'] for e in entities])}\n"
                f"Shared components: {json.dumps(shared_components)}"
            )
            logger.info("ProjectFolderCreator: generating shared files via LLM")
            raw = self._llm.complete(_SYSTEM_SHARED, user_prompt, max_tokens=4000)
            result = safe_extract_json(raw, fallback={"files": []})
            self._write_files(shared_dir, result.get("files", []), file_log, folder_log)
        else:
            self._write_fallback_shared(shared_dir, tech_stack, modules, entities, file_log, folder_log)

    def _generate_metadata(self, project_root, project_name, tech_stack, modules, entities, features, shared_components, folder_log, file_log):
        metadata_dir = os.path.join(project_root, "metadata")
        self._ensure_dir(metadata_dir, folder_log)

        # tech_stack_summary.json
        self._write_file(
            os.path.join(metadata_dir, "tech_stack_summary.json"),
            json.dumps({
                "project_name": project_name,
                "tech_stack": tech_stack,
                "modules": [m["name"] for m in modules],
                "entities": [e["name"] for e in entities],
                "features": [f["name"] for f in features],
            }, indent=2) + "\n",
            file_log,
        )

        # shared_components_registry.json
        self._write_file(
            os.path.join(metadata_dir, "shared_components_registry.json"),
            json.dumps({"shared_components": shared_components}, indent=2) + "\n",
            file_log,
        )

        # .env.example
        safe_name = self._safe_name(project_name)
        db = tech_stack.get("database", "postgresql")
        if "mongo" in db.lower():
            db_url = f"mongodb://localhost:27017/{safe_name}"
        elif "mysql" in db.lower():
            db_url = f"mysql://user:password@localhost:3306/{safe_name}"
        else:
            db_url = f"postgresql://user:password@localhost:5432/{safe_name}"

        self._write_file(
            os.path.join(project_root, ".env.example"),
            f"# {project_name} — environment variables\n"
            f"DATABASE_URL={db_url}\n"
            f"SECRET_KEY=change-me-in-production\n"
            f"DEBUG=true\n"
            f"LOG_LEVEL=INFO\n",
            file_log,
        )

        # README.md
        self._write_file(
            os.path.join(project_root, "README.md"),
            f"# {project_name}\n\n"
            f"Generated project scaffold.\n\n"
            f"## Tech Stack\n"
            f"- Backend:        {tech_stack.get('backend')}\n"
            f"- Frontend:       {tech_stack.get('frontend')}\n"
            f"- Database:       {tech_stack.get('database')}\n"
            f"- Infrastructure: {tech_stack.get('infrastructure')}\n\n"
            f"## Structure\n"
            "```\n"
            "outputs/\n"
            "  backend/    # server-side application\n"
            "  frontend/   # client-side application\n"
            "  database/   # schema, migrations, seeds\n"
            "  shared/     # cross-cutting utilities and contracts\n"
            "  metadata/   # tech stack summary and component registry\n"
            "```\n",
            file_log,
        )

    # ------------------------------------------------------------------
    # Fallback writers (used when no LLM is available)
    # ------------------------------------------------------------------

    def _write_fallback_backend(self, backend_dir, tech_stack, modules, entities, file_log, folder_log):
        backend = tech_stack.get("backend", "python").lower()
        if "fastapi" in backend or "python" in backend:
            files = {
                "main.py": "from fastapi import FastAPI\napp = FastAPI()\n\n@app.get('/health')\ndef health(): return {'status': 'ok'}\n",
                "requirements.txt": "fastapi\nuvicorn\npydantic\npsycopg2-binary\n",
                "config.py": "import os\nDATABASE_URL = os.getenv('DATABASE_URL', '')\nSECRET_KEY = os.getenv('SECRET_KEY', '')\n",
            }
        elif "node" in backend or "express" in backend:
            files = {
                "index.js": "const express = require('express');\nconst app = express();\napp.get('/health', (req, res) => res.json({ status: 'ok' }));\napp.listen(3001);\n",
                "package.json": '{"name":"backend","version":"1.0.0","dependencies":{"express":"^4.18.2"}}\n',
            }
        else:
            files = {"main.py": "# Entry point\n", "requirements.txt": "# dependencies\n"}

        for rel, content in files.items():
            self._write_file(os.path.join(backend_dir, rel), content, file_log)

        for module in modules:
            mod_name = self._safe_name(module.get("name", "module"))
            mod_dir = os.path.join(backend_dir, mod_name)
            self._ensure_dir(mod_dir, folder_log)
            self._write_file(os.path.join(mod_dir, "__init__.py"), "", file_log)
            self._write_file(os.path.join(mod_dir, "service.py"), f"# {module.get('name')} service\n", file_log)
            self._write_file(os.path.join(mod_dir, "models.py"), f"# {module.get('name')} models\n", file_log)
            self._write_file(os.path.join(mod_dir, "routes.py"), f"# {module.get('name')} routes\n", file_log)

    def _write_fallback_frontend(self, frontend_dir, tech_stack, features, file_log, folder_log):
        frontend = tech_stack.get("frontend", "react").lower()
        if "react" in frontend or "next" in frontend:
            self._write_file(os.path.join(frontend_dir, "package.json"), '{"name":"frontend","version":"0.1.0","dependencies":{"react":"^18.2.0","react-dom":"^18.2.0"}}\n', file_log)
            src_dir = os.path.join(frontend_dir, "src")
            self._ensure_dir(src_dir, folder_log)
            self._write_file(os.path.join(src_dir, "App.jsx"), "export default function App() { return <h1>Welcome</h1>; }\n", file_log)
            self._write_file(os.path.join(src_dir, "index.jsx"), "import React from 'react'; import ReactDOM from 'react-dom/client'; import App from './App';\nReactDOM.createRoot(document.getElementById('root')).render(<App />);\n", file_log)
        elif "vue" in frontend:
            self._write_file(os.path.join(frontend_dir, "package.json"), '{"name":"frontend","version":"0.1.0","dependencies":{"vue":"^3.3.0"}}\n', file_log)

    def _write_fallback_database(self, database_dir, entities, file_log):
        lines = []
        for entity in entities:
            name = entity.get("name", "item").lower()
            lines.append(f"CREATE TABLE {name}s (")
            lines.append("  id SERIAL PRIMARY KEY,")
            for attr in entity.get("attributes", []):
                lines.append(f"  {attr['name']} VARCHAR(255),")
            lines.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
            lines.append(");\n")
        self._write_file(os.path.join(database_dir, "schema.sql"), "\n".join(lines), file_log)
        self._write_file(os.path.join(database_dir, "seed.sql"), "-- seed data\n", file_log)

    def _write_fallback_shared(self, shared_dir, tech_stack, modules, entities, file_log, folder_log):
        backend = tech_stack.get("backend", "python").lower()
        use_py = "node" not in backend and "express" not in backend

        if use_py:
            self._write_file(os.path.join(shared_dir, "constants.py"), "DEFAULT_PAGE_SIZE = 20\nAPI_VERSION = 'v1'\n", file_log)
            self._write_file(os.path.join(shared_dir, "exceptions.py"), "class AppError(Exception): pass\nclass NotFoundError(AppError): pass\n", file_log)
        else:
            self._write_file(os.path.join(shared_dir, "constants.js"), "module.exports = { DEFAULT_PAGE_SIZE: 20, API_VERSION: 'v1' };\n", file_log)

        contracts_dir = os.path.join(shared_dir, "contracts")
        self._ensure_dir(contracts_dir, folder_log)
        for module in modules:
            name = self._safe_name(module.get("name", "module"))
            contract = {
                "module": module.get("name"),
                "endpoints": [
                    {"method": "GET", "path": f"/api/v1/{name}"},
                    {"method": "POST", "path": f"/api/v1/{name}"},
                    {"method": "GET", "path": f"/api/v1/{name}/{{id}}"},
                    {"method": "PUT", "path": f"/api/v1/{name}/{{id}}"},
                    {"method": "DELETE", "path": f"/api/v1/{name}/{{id}}"},
                ],
            }
            self._write_file(
                os.path.join(contracts_dir, f"{name}_contract.json"),
                json.dumps(contract, indent=2) + "\n",
                file_log,
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _build_context(self, project_name, tech_stack, modules, entities, features) -> str:
        return (
            f"Project: {project_name}\n"
            f"Tech stack: {json.dumps(tech_stack)}\n"
            f"Modules: {json.dumps([m['name'] for m in modules])}\n"
            f"Entities: {json.dumps([e['name'] for e in entities])}\n"
            f"Features: {json.dumps([f['name'] for f in features])}"
        )

    def _write_files(self, base_dir: str, files: List[Dict], file_log: List, folder_log: List) -> None:
        for file_entry in files:
            rel_path = file_entry.get("path", "")
            content = file_entry.get("content", "")
            if not rel_path:
                continue
            abs_path = os.path.join(base_dir, rel_path.replace("/", os.sep))
            parent = os.path.dirname(abs_path)
            self._ensure_dir(parent, folder_log)
            self._write_file(abs_path, content, file_log)

    @staticmethod
    def _ensure_dir(path: str, log: List) -> None:
        os.makedirs(path, exist_ok=True)
        if path not in log:
            log.append(path)

    @staticmethod
    def _write_file(path: str, content: str, log: List) -> None:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        log.append(path)

    @staticmethod
    def _safe_name(name: str) -> str:
        import re
        return re.sub(r"[^A-Za-z0-9_-]", "_", name).strip("_").lower() or "module"
