"""add_final_governance_audits_table

Revision ID: 6f688358ebe7
Revises: 7e618895d25d
Create Date: 2026-07-29 05:59:41.451826+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
# pyrefly: ignore [missing-module-attribute]
from alembic import op
from sqlalchemy.dialects import postgresql
import app
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '6f688358ebe7'
down_revision: Union[str, None] = '7e618895d25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_governance_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('story_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('metadata', app.database.types.JsonDict(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_governance_audits_project_id'), 'final_governance_audits', ['project_id'], unique=False)
    op.drop_index(op.f('ix_releases_project_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_table('workspace_registries')
    op.drop_index(op.f('ix_visualizations_project_id'), table_name='visualizations')
    op.drop_table('visualizations')
    op.drop_table('merge_queue_records')
    op.drop_index(op.f('ix_migration_plans_project_id'), table_name='migration_plans')
    op.drop_table('migration_plans')
    op.alter_column('artifacts', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'requirements_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=app.database.types.JsonDict(),
               existing_nullable=True)
    op.drop_column('user_stories', 'export_status')
    op.drop_column('user_stories', 'retry_count')
    op.drop_column('user_stories', 'merge_status')
    op.drop_column('user_stories', 'execution_timestamp')
    op.drop_column('user_stories', 'version')
    op.drop_column('user_stories', 'validation_status')
    op.drop_column('user_stories', 'preview_status')
    op.drop_column('user_stories', 'generation_status')
    op.drop_column('user_stories', 'assigned_agent')
    op.drop_column('user_stories', 'audit_trail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('audit_trail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('assigned_agent', sa.VARCHAR(length=50), server_default=sa.text("'Agent2'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('generation_status', sa.VARCHAR(length=50), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('preview_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('validation_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('version', sa.VARCHAR(length=20), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('execution_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('merge_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('export_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('projects', 'requirements_json',
               existing_type=app.database.types.JsonDict(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('artifacts', 'project_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_table('migration_plans',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('migration_plan_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_order_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('migration_plans_pkey'))
    )
    op.create_index(op.f('ix_migration_plans_project_id'), 'migration_plans', ['project_id'], unique=False)
    op.create_table('merge_queue_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_log', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('rollback_checkpoint_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('merge_queue_records_pkey'))
    )
    op.create_table('visualizations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('visualization_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('preview_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('project_tree_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('er_diagram_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('component_graph_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('api_graph_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('viz_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preview_assets_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('url_map_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('visualizations_pkey'))
    )
    op.create_index(op.f('ix_visualizations_project_id'), 'visualizations', ['project_id'], unique=False)
    op.create_table('workspace_registries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('workspace_root', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_registries_pkey'))
    )
    op.create_table('releases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('archive_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('export_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('release_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manifest_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('releases_pkey'))
    )
    op.create_index(op.f('ix_releases_project_id'), 'releases', ['project_id'], unique=False)
    op.drop_index(op.f('ix_final_governance_audits_project_id'), table_name='final_governance_audits')
    op.drop_table('final_governance_audits')
    # ### end Alembic commands ###
