"""consolidated_tables_and_prompts

Revision ID: 78dd7c851280
Revises: a1b2c3d4e5f6
Create Date: 2026-07-28 07:36:20.632071+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
import app
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78dd7c851280'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop foreign key constraints first to allow altering columns
    try:
        op.drop_constraint('artifacts_project_id_fkey', 'artifacts', type_='foreignkey')
    except Exception:
        pass
    try:
        op.drop_constraint('artifacts_story_id_fkey', 'artifacts', type_='foreignkey')
    except Exception:
        pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_validations_story_id'), table_name='story_validations')
    op.drop_table('story_validations')
    op.drop_index(op.f('ix_validation_results_story_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_validation_type'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_table('preview_session_records')
    op.drop_table('migration_plan_records')
    op.drop_index(op.f('ix_artifact_contents_artifact_id'), table_name='artifact_contents')
    op.drop_table('artifact_contents')
    op.drop_index(op.f('ix_story_approvals_story_id'), table_name='story_approvals')
    op.drop_table('story_approvals')
    op.drop_index(op.f('ix_story_executions_story_id'), table_name='story_executions')
    op.drop_table('story_executions')
    op.drop_table('release_history_records')
    op.drop_table('generated_file_registries')
    op.drop_table('project_health_records')
    op.drop_index(op.f('ix_story_audits_story_id'), table_name='story_audits')
    op.drop_table('story_audits')
    op.drop_table('execution_timeline_records')
    op.drop_table('story_feedbacks')
    op.drop_table('agent_execution_metrics')
    op.drop_index(op.f('ix_story_merges_story_id'), table_name='story_merges')
    op.drop_table('story_merges')
    op.drop_index(op.f('ix_story_exports_project_id'), table_name='story_exports')
    op.drop_table('story_exports')
    op.drop_table('visualization_metadata_records')
    op.drop_index(op.f('ix_dependencies_component_id'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_dependency_type'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_depends_on_component_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_table('shared_artifact_registry_records')
    op.drop_table('file_version_histories')
    op.drop_index(op.f('ix_file_history_file_id'), table_name='file_history')
    op.drop_table('file_history')
    op.drop_table('story_revisions')
    op.drop_index(op.f('ix_story_versions_story_id'), table_name='story_versions')
    op.drop_table('story_versions')
    op.drop_table('dependency_graph_records')
    op.drop_index(op.f('ix_files_component_id'), table_name='files')
    op.drop_index(op.f('ix_files_story_id'), table_name='files')
    op.drop_table('files')
    op.add_column('artifacts', sa.Column('id', app.database.types.GUID(), nullable=False))
    op.add_column('artifacts', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('artifacts', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('artifacts', sa.Column('owner_story', sa.String(length=50), nullable=True))
    op.add_column('artifacts', sa.Column('shared_flag', sa.Boolean(), nullable=True))
    op.add_column('artifacts', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('artifacts', sa.Column('usage_references_json', sa.JSON(), nullable=True))
    op.add_column('artifacts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('artifacts', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('artifacts', 'file_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('artifacts', 'checksum',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'artifacts', 'user_stories', ['story_id'], ['story_id'], ondelete='CASCADE')
    op.drop_column('artifacts', 'artifact_name')
    op.drop_column('artifacts', 'artifact_id')
    op.drop_column('artifacts', 'artifact_type')
    op.drop_column('blueprints', 'workflow_blueprint')
    op.drop_column('blueprints', 'api_blueprint')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_column('projects', 'status')
    op.drop_column('prompt_approvals', 'bundle_json')
    op.alter_column('user_stories', 'story_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_stories_epic_id'), table_name='user_stories')
    op.drop_index(op.f('ix_stories_status'), table_name='user_stories')
    op.drop_index(op.f('ix_stories_story_key'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_approval_status'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_story_id'), table_name='user_stories')
    op.create_index(op.f('ix_user_stories_epic_id'), 'user_stories', ['epic_id'], unique=False)
    op.create_index(op.f('ix_user_stories_story_key'), 'user_stories', ['story_key'], unique=True)
    op.drop_column('user_stories', 'assigned_agent')
    op.drop_column('user_stories', 'audit_trail')
    op.drop_column('user_stories', 'generation_status')
    op.drop_column('user_stories', 'merge_status')
    op.drop_column('user_stories', 'retry_count')
    op.drop_column('user_stories', 'approved')
    op.drop_column('user_stories', 'preview_status')
    op.drop_column('user_stories', 'version')
    op.drop_column('user_stories', 'execution_timestamp')
    op.drop_column('user_stories', 'validation_status')
    op.drop_column('user_stories', 'export_status')
    op.drop_column('user_stories', 'approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('approval_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('export_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('validation_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('execution_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('preview_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_stories', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('merge_status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('generation_status', sa.VARCHAR(length=50), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('audit_trail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_stories', sa.Column('assigned_agent', sa.VARCHAR(length=50), server_default=sa.text("'Agent2'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_stories_story_key'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_epic_id'), table_name='user_stories')
    op.create_index(op.f('ix_user_stories_story_id'), 'user_stories', ['story_id'], unique=False)
    op.create_index(op.f('ix_user_stories_approval_status'), 'user_stories', ['approval_status'], unique=False)
    op.create_index(op.f('ix_stories_story_key'), 'user_stories', ['story_key'], unique=True)
    op.create_index(op.f('ix_stories_status'), 'user_stories', ['approval_status'], unique=False)
    op.create_index(op.f('ix_stories_epic_id'), 'user_stories', ['epic_id'], unique=False)
    op.alter_column('user_stories', 'story_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('prompt_approvals', sa.Column('bundle_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.add_column('blueprints', sa.Column('api_blueprint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('blueprints', sa.Column('workflow_blueprint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('artifact_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('artifacts', sa.Column('artifact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.add_column('artifacts', sa.Column('artifact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('artifacts_story_id_fkey'), 'artifacts', 'user_stories', ['story_id'], ['story_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('artifacts_project_id_fkey'), 'artifacts', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.alter_column('artifacts', 'checksum',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('artifacts', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('artifacts', 'project_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               nullable=False)
    op.drop_column('artifacts', 'created_at')
    op.drop_column('artifacts', 'usage_references_json')
    op.drop_column('artifacts', 'content')
    op.drop_column('artifacts', 'shared_flag')
    op.drop_column('artifacts', 'owner_story')
    op.drop_column('artifacts', 'category')
    op.drop_column('artifacts', 'name')
    op.drop_column('artifacts', 'id')
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('files_component_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('files_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey'))
    )
    op.create_index(op.f('ix_files_story_id'), 'files', ['story_id'], unique=False)
    op.create_index(op.f('ix_files_component_id'), 'files', ['component_id'], unique=False)
    op.create_table('dependency_graph_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dependency_graph_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_order_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dependency_graph_records_pkey'))
    )
    op.create_table('story_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('code_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('story_versions_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_versions_pkey'))
    )
    op.create_index(op.f('ix_story_versions_story_id'), 'story_versions', ['story_id'], unique=False)
    op.create_table('story_revisions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('files_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('story_revisions_pkey'))
    )
    op.create_table('file_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modified_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('file_history_file_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_history_pkey'))
    )
    op.create_index(op.f('ix_file_history_file_id'), 'file_history', ['file_id'], unique=False)
    op.create_table('file_version_histories',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('file_registry_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('file_version_histories_pkey'))
    )
    op.create_table('shared_artifact_registry_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('owner_story', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('usage_references_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_artifact_registry_records_pkey'))
    )
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('depends_on_component_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dependency_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('dependencies_component_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_component_id'], ['components.id'], name=op.f('dependencies_depends_on_component_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dependencies_pkey'))
    )
    op.create_index(op.f('ix_dependencies_depends_on_component_id'), 'dependencies', ['depends_on_component_id'], unique=False)
    op.create_index(op.f('ix_dependencies_dependency_type'), 'dependencies', ['dependency_type'], unique=False)
    op.create_index(op.f('ix_dependencies_component_id'), 'dependencies', ['component_id'], unique=False)
    op.create_table('visualization_metadata_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('visualization_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('viz_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('visualization_metadata_records_pkey'))
    )
    op.create_table('story_exports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('zip_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('story_exports_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_exports_pkey'))
    )
    op.create_index(op.f('ix_story_exports_project_id'), 'story_exports', ['project_id'], unique=False)
    op.create_table('story_merges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('merged_files', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('story_merges_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_merges_pkey'))
    )
    op.create_index(op.f('ix_story_merges_story_id'), 'story_merges', ['story_id'], unique=False)
    op.create_table('agent_execution_metrics',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('execution_state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('inputs_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outputs_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timings_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('retries_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_execution_metrics_pkey'))
    )
    op.create_table('story_feedbacks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reviewer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('story_feedbacks_pkey'))
    )
    op.create_table('execution_timeline_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scheduler_state_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timeline_events_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('execution_timeline_records_pkey'))
    )
    op.create_table('story_audits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('agent', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('previous_state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('new_state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('story_audits_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_audits_pkey'))
    )
    op.create_index(op.f('ix_story_audits_story_id'), 'story_audits', ['story_id'], unique=False)
    op.create_table('project_health_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('build_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('validation_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('security_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('test_coverage', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('metrics_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('project_health_records_pkey'))
    )
    op.create_table('generated_file_registries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('relative_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ownership', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('merge_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_file_registries_pkey'))
    )
    op.create_table('release_history_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('archive_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('release_notes', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('manifest_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('release_history_records_pkey'))
    )
    op.create_table('story_executions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('execution_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('story_executions_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_executions_pkey'))
    )
    op.create_index(op.f('ix_story_executions_story_id'), 'story_executions', ['story_id'], unique=False)
    op.create_table('story_approvals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reviewer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('story_approvals_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_approvals_pkey'))
    )
    op.create_index(op.f('ix_story_approvals_story_id'), 'story_approvals', ['story_id'], unique=False)
    op.create_table('artifact_contents',
    sa.Column('content_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('artifact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], name=op.f('artifact_contents_artifact_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', name=op.f('artifact_contents_pkey'))
    )
    op.create_index(op.f('ix_artifact_contents_artifact_id'), 'artifact_contents', ['artifact_id'], unique=False)
    op.create_table('migration_plan_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('migration_plan_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_order_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('migration_plan_records_pkey'))
    )
    op.create_table('preview_session_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('story_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('preview_assets_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('url_map_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('preview_session_records_pkey'))
    )
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('validation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('validation_results_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validation_results_pkey'))
    )
    op.create_index(op.f('ix_validation_results_validation_type'), 'validation_results', ['validation_type'], unique=False)
    op.create_index(op.f('ix_validation_results_story_id'), 'validation_results', ['story_id'], unique=False)
    op.create_table('story_validations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('validation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.story_id'], name=op.f('story_validations_story_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('story_validations_pkey'))
    )
    op.create_index(op.f('ix_story_validations_story_id'), 'story_validations', ['story_id'], unique=False)
    # ### end Alembic commands ###
