"""add_tech_stack_to_projects

Revision ID: 6fa3061d758d
Revises: 0001
Create Date: 2026-07-22 09:19:24.440560+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6fa3061d758d'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('epics_epic_key_key'), 'epics', type_='unique')
    op.drop_index(op.f('ix_epics_epic_key'), table_name='epics')
    op.create_index(op.f('ix_epics_epic_key'), 'epics', ['epic_key'], unique=True)
    op.add_column('projects', sa.Column('tech_stack', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('stories_story_key_key'), 'stories', type_='unique')
    op.drop_index(op.f('ix_stories_story_key'), table_name='stories')
    op.create_index(op.f('ix_stories_story_key'), 'stories', ['story_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_story_key'), table_name='stories')
    op.create_index(op.f('ix_stories_story_key'), 'stories', ['story_key'], unique=False)
    op.create_unique_constraint(op.f('stories_story_key_key'), 'stories', ['story_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'tech_stack')
    op.drop_index(op.f('ix_epics_epic_key'), table_name='epics')
    op.create_index(op.f('ix_epics_epic_key'), 'epics', ['epic_key'], unique=False)
    op.create_unique_constraint(op.f('epics_epic_key_key'), 'epics', ['epic_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
