"""Routing Generator for producing React Router v6 TypeScript route configurations."""

import logging
from typing import Any, Dict, List

from agents.agent0_wireframe.screen_detector import DetectedScreen

logger = logging.getLogger(__name__)


class RoutingGenerator:
    """Generates React Router v6 TSX routing code and layout routes."""

    def generate_routes_code(self, screens: List[DetectedScreen]) -> str:
        """Generate clean, production-ready React Router v6 TypeScript code."""
        imports = [
            "import React, { lazy, Suspense } from 'react';",
            "import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';",
            "import MainLayout from '../layouts/MainLayout';",
        ]

        lazy_imports = []
        route_elements = []

        for screen in screens:
            lazy_imports.append(
                f"const {screen.component_name} = lazy(() => import('../pages/{screen.component_name}'));"
            )
            route_elements.append(
                f"          <Route path=\"{screen.route_path}\" element=<{screen.component_name} /> />"
            )

        code_lines = [
            "// Generated by Agent-0 Routing Generator (React Router v6)",
            *imports,
            "",
            "// Lazy-loaded page components",
            *lazy_imports,
            "",
            "export const AppRoutes: React.FC = () => {",
            "  return (",
            "    <BrowserRouter>",
            "      <Suspense fallback={<div className=\"flex items-center justify-center h-screen\">Loading...</div>}>",
            "        <Routes>",
            "          <Route element={<MainLayout />}>",
            *route_elements,
            "          </Route>",
            "          <Route path=\"*\" element={<Navigate to=\"/\" replace />} />",
            "        </Routes>",
            "      </Suspense>",
            "    </BrowserRouter>",
            "  );",
            "};",
            "",
            "export default AppRoutes;",
        ]

        return "\n".join(code_lines)
