"""Tests for LLM execution-mode retry and fallback policy."""

import httpx
import pytest

from app.utils import llm_client
from app.utils.llm_client import LLMClient


def _messages() -> list[dict[str, str]]:
    return [
        {
            "role": "system",
            "content": "You are an expert Business Analyst and Requirements Engineer.",
        },
        {"role": "user", "content": "Analyse one user story."},
    ]


def _install_responses(monkeypatch, responses):
    """Replace httpx.Client with a context manager returning queued responses."""
    sent = []

    class StubClient:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def post(self, *_args, **_kwargs):
            sent.append(True)
            return responses.pop(0)

    monkeypatch.setattr(llm_client.httpx, "Client", lambda **_kwargs: StubClient())
    return sent


def test_development_mode_falls_back_to_mock_on_groq_rate_limit(monkeypatch, caplog):
    monkeypatch.setenv("LLM_MODE", "development")
    monkeypatch.setattr(llm_client.time, "sleep", lambda _seconds: None)
    sent = _install_responses(monkeypatch, [httpx.Response(429)])

    reply = LLMClient(provider="groq", api_key="test-key").chat(_messages())

    assert '"stories"' in reply
    assert len(sent) == 1
    assert "falling back to mock" in caplog.text
    assert "mock provider (Groq rate-limit fallback)" in caplog.text


def test_development_mode_uses_mock_when_explicitly_selected(monkeypatch, caplog):
    monkeypatch.setenv("LLM_MODE", "development")

    reply = LLMClient(provider="mock").chat(_messages())

    assert '"stories"' in reply
    assert "mock provider (mock provider selected)" in caplog.text


def test_production_mode_retries_groq_rate_limits_without_mock(monkeypatch, caplog):
    monkeypatch.setenv("LLM_MODE", "production")
    monkeypatch.setattr(llm_client.time, "sleep", lambda _seconds: None)
    sent = _install_responses(
        monkeypatch,
        [
            httpx.Response(429, headers={"retry-after": "0"}),
            httpx.Response(200, json={"choices": [{"message": {"content": "Groq reply"}}]}),
        ],
    )

    client = LLMClient(provider="groq", api_key="test-key")
    client.MAX_RETRIES = 2
    reply = client.chat(_messages())

    assert reply == "Groq reply"
    assert len(sent) == 2
    assert "falling back to mock" not in caplog.text
    assert "generated by groq provider" in caplog.text


def test_production_mode_errors_after_rate_limit_retries(monkeypatch):
    monkeypatch.setenv("LLM_MODE", "production")
    monkeypatch.setattr(llm_client.time, "sleep", lambda _seconds: None)
    _install_responses(monkeypatch, [httpx.Response(429), httpx.Response(429)])

    client = LLMClient(provider="groq", api_key="test-key")
    client.MAX_RETRIES = 2

    with pytest.raises(RuntimeError, match="LLM call failed after 2 attempts"):
        client.chat(_messages())


def test_production_mode_retries_transient_server_failures(monkeypatch):
    monkeypatch.setenv("LLM_MODE", "production")
    monkeypatch.setattr(llm_client.time, "sleep", lambda _seconds: None)
    sent = _install_responses(
        monkeypatch,
        [
            httpx.Response(503, text="service unavailable"),
            httpx.Response(200, json={"choices": [{"message": {"content": "Recovered"}}]}),
        ],
    )

    client = LLMClient(provider="groq", api_key="test-key")
    client.MAX_RETRIES = 2

    assert client.chat(_messages()) == "Recovered"
    assert len(sent) == 2
