"""TodoApp Agent-3 Merge Utility.

Merges approved TodoApp stories from backend/workspace/TodoApp/US001..US010
into backend/integrated_project/TodoApp/.
"""

import json
import shutil
import logging
from pathlib import Path
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent.parent.parent
WORKSPACE_DIR = BASE_DIR / "workspace" / "TodoApp"
INTEGRATED_DIR = BASE_DIR / "integrated_project" / "TodoApp"


def merge_approved_todo_app() -> Dict[str, Any]:
    """Merge approved user story workspaces into backend/integrated_project/TodoApp."""
    if not WORKSPACE_DIR.exists():
        return {"success": False, "message": "TodoApp workspace does not exist."}

    INTEGRATED_DIR.mkdir(parents=True, exist_ok=True)
    int_frontend = INTEGRATED_DIR / "frontend"
    int_backend = INTEGRATED_DIR / "backend"
    int_db = INTEGRATED_DIR / "database"

    int_frontend.mkdir(parents=True, exist_ok=True)
    int_backend.mkdir(parents=True, exist_ok=True)
    int_db.mkdir(parents=True, exist_ok=True)

    merged_stories = []
    merged_files_count = 0

    for sdir in sorted(WORKSPACE_DIR.glob("US*")):
        if not sdir.is_dir():
            continue

        meta_file = sdir / "metadata.json"
        is_approved = False
        if meta_file.exists():
            try:
                with open(meta_file, "r", encoding="utf-8") as f:
                    meta = json.load(f)
                    status = meta.get("status", "").upper()
                    approval_status = meta.get("approval_status", "").upper()
                    if status == "APPROVED" or approval_status == "APPROVED":
                        is_approved = True
            except Exception as e:
                logger.error("Error reading %s: %s", meta_file, e)

        # Merge approved story files
        if is_approved:
            story_id = sdir.name
            merged_stories.append(story_id)

            # Copy frontend files
            src_fe = sdir / "frontend"
            if src_fe.exists():
                for item in src_fe.glob("*"):
                    if item.is_file():
                        shutil.copy(item, int_frontend / item.name)
                        merged_files_count += 1

            # Copy backend files
            src_be = sdir / "backend"
            if src_be.exists():
                for item in src_be.glob("*"):
                    if item.is_file():
                        shutil.copy(item, int_backend / item.name)
                        merged_files_count += 1

    # Generate integrated project configuration files
    package_json = {
        "name": "todo-app-integrated",
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "dev": "vite",
            "build": "tsc && vite build"
        },
        "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "lucide-react": "^0.300.0"
        }
    }

    requirements_txt = """fastapi>=0.100.0
uvicorn>=0.22.0
pydantic>=2.0.0
sqlalchemy>=2.0.0
"""

    readme_md = f"""# TodoApp Integrated Project

Generated by CD-SE Accelerators Agent-3 Pipeline.

## Structure
- `frontend/`: React components from approved user stories ({', '.join(merged_stories)})
- `backend/`: FastAPI routers and services from approved user stories
- `database/`: Database schema and migrations

## Quick Start
1. Backend: `pip install -r requirements.txt && uvicorn main:app --reload`
2. Frontend: `npm install && npm run dev`
"""

    with open(INTEGRATED_DIR / "package.json", "w", encoding="utf-8") as f:
        json.dump(package_json, f, indent=2)
    merged_files_count += 1

    with open(INTEGRATED_DIR / "requirements.txt", "w", encoding="utf-8") as f:
        f.write(requirements_txt)
    merged_files_count += 1

    with open(INTEGRATED_DIR / "README.md", "w", encoding="utf-8") as f:
        f.write(readme_md)
    merged_files_count += 1

    merge_manifest = {
        "project_name": "TodoApp",
        "merged_stories": merged_stories,
        "total_merged_stories": len(merged_stories),
        "total_merged_files": merged_files_count,
        "integrated_path": str(INTEGRATED_DIR),
        "status": "SUCCESS"
    }

    with open(INTEGRATED_DIR / "MergeManifest.json", "w", encoding="utf-8") as f:
        json.dump(merge_manifest, f, indent=2)

    return {
        "success": True,
        "message": f"Successfully merged {len(merged_stories)} approved user stories into backend/integrated_project/TodoApp",
        "merged_stories": merged_stories,
        "merged_files_count": merged_files_count
    }
