"""
Pipeline Orchestrator Models – Development & Testing.

Defines Pydantic schemas for the Pipeline Orchestrator endpoint POST /pipeline/run.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class PipelineRunRequest(BaseModel):
    """Payload to trigger end-to-end pipeline orchestration for development testing."""

    project_path: str = Field(..., description="Absolute or relative path to target project directory.")
    pipeline_run_id: Optional[str] = Field(None, description="Unique pipeline run identifier.")
    project_id: Optional[str] = Field(None, description="Target database project ID to attach execution artifacts to.")
    project_name: Optional[str] = Field(None, description="Human-friendly project name given by user in UI.")
    run_until: str = Field(
        "validation",
        description="Target stage to stop pipeline execution at. Supported values: "
                    "source_ingestion, framework_detection (framework), project_analyzer (analysis), "
                    "ir_generator (ir), strategy_generator (strategy), edge_case_generator (edge_case), "
                    "test_case_generator (test_case), test_writer, test_execution, validation."
    )
    include_timings: bool = Field(True, description="Whether to include stage execution timing breakdown in milliseconds.")
    include_intermediate_outputs: bool = Field(True, description="Whether to include intermediate stage artifacts in outputs dict.")


class PerformanceMetrics(BaseModel):
    """Detailed pipeline performance metrics and timing breakdown."""

    ingestion_time_ms: float = Field(0.0, description="Source ingestion duration in ms.")
    project_scan_time_ms: float = Field(0.0, description="Fast project scanner duration in ms.")
    framework_detection_time_ms: float = Field(0.0, description="Deterministic framework detection duration in ms.")
    indexing_time_ms: float = Field(0.0, description="Project index generation duration in ms.")
    cache_lookup_time_ms: float = Field(0.0, description="Cache check & file hash lookup duration in ms.")
    component_analysis_time_ms: float = Field(0.0, description="Component analysis duration in ms.")
    llm_time_ms: float = Field(0.0, description="LLM/reasoning engine duration in ms.")
    test_case_generation_time_ms: float = Field(0.0, description="Test case generation duration in ms.")
    test_writer_time_ms: float = Field(0.0, description="Test suite code generation duration in ms.")
    total_pipeline_time_ms: float = Field(0.0, description="Total pipeline execution time in ms.")

    total_files_scanned: int = Field(0, description="Total files encountered during directory walk.")
    relevant_files: int = Field(0, description="Number of relevant source files indexed.")
    ignored_files: int = Field(0, description="Number of files skipped due to ignore patterns.")
    cached_files: int = Field(0, description="Number of files/components reused from cache.")
    files_analyzed: int = Field(0, description="Number of files/components parsed/analyzed.")
    llm_calls: int = Field(0, description="Total LLM requests triggered.")
    parallel_tasks: int = Field(0, description="Number of concurrent component tasks executed.")
    cache_hit_rate: float = Field(0.0, description="Percentage of component analyses served from cache.")

    discovered_components: int = Field(0, description="Number of components discovered by the full AST parser.")
    analyzed_components: int = Field(0, description="Number of components included in the final analysis output.")
    skipped_components: int = Field(0, description="Number of scanner-listed source files not found as components by parser.")
    generated_test_cases: int = Field(0, description="Total test cases generated by the pipeline.")
    duplicate_cases_removed: int = Field(0, description="Number of duplicate test cases removed during deduplication.")


class PipelineOutputs(BaseModel):
    """Grouped artifact outputs generated by the pipeline stages."""

    framework: Optional[str] = Field(None, description="Detected frontend framework name.")
    workspace_path: Optional[str] = Field(None, description="Active workspace path.")
    project_path: Optional[str] = Field(None, description="Project root path.")
    analysis: Optional[Dict[str, Any]] = Field(None, description="Structured project analysis output.")
    frontend_context: Optional[Dict[str, Any]] = Field(None, description="Frontend Context Extraction Engine representation.")
    behavior_inventory: Optional[Dict[str, Any]] = Field(None, description="Frontend Behavior Inventory representation.")
    ir: Optional[Dict[str, Any]] = Field(None, description="Framework-agnostic intermediate representation.")
    strategy_plan: Optional[Dict[str, Any]] = Field(None, description="Generated test strategy plan.")
    edge_case_plan: Optional[Dict[str, Any]] = Field(None, description="Generated edge case scenario plan.")
    test_case_plan: Optional[Dict[str, Any]] = Field(None, description="Generated structured test case plan.")
    generated_test_files: Optional[Dict[str, Any]] = Field(None, description="Framework-specific compiled test files.")
    execution_report: Optional[Dict[str, Any]] = Field(None, description="Test execution report summary.")
    test_report: Optional[Dict[str, Any]] = Field(None, description="Human-friendly test execution and quality report.")
    validation_report: Optional[Dict[str, Any]] = Field(None, description="Validation and QA report summary.")
    performance_metrics: Optional[PerformanceMetrics] = Field(None, description="Detailed performance metrics.")


class PipelineRunResponse(BaseModel):
    """Overall response payload returned by the pipeline orchestrator endpoint."""

    status: str = Field(..., description="Pipeline execution status: 'success' or 'failed'.")
    pipeline_run_id: Optional[str] = Field(None, description="Unique pipeline run identifier.")
    project_id: Optional[str] = Field(None, description="Unique project identifier.")
    completed_stages: List[str] = Field(default_factory=list, description="Ordered list of successfully executed pipeline stages.")
    outputs: PipelineOutputs = Field(default_factory=PipelineOutputs, description="Grouped artifact outputs.")
    total_execution_time_ms: float = Field(0.0, description="Total pipeline execution duration in milliseconds.")
    stage_execution_times_ms: Optional[Dict[str, float]] = Field(None, description="Timing breakdown per stage in milliseconds.")
    performance_metrics: Optional[PerformanceMetrics] = Field(None, description="Performance metrics breakdown.")
    failed_stage: Optional[str] = Field(None, description="Name of the stage that failed, if any.")
    error_message: Optional[str] = Field(None, description="Detailed error message if execution failed.")
    traceback: Optional[str] = Field(None, description="Python exception traceback if execution failed.")
